import React from 'react';
import { Tab, Box } from '@mui/material';
import { TabContext, TabList } from '@mui/lab';

import './PlantasTabla.css';
import TablaElementosTabla from '../components/TablaElementosTabla';

function PlantasTabla() {

    const planta = {
        idCliente: '',
        nombreCliente: '',
        elementos: [{
            nombre: 'Refrigeración',
            numero: 1,
            posicion: 1,
            nivel: 1,
            propiedades: {
                fisicoQuimico: true,
                aerobios: false,
                legionela: true,
                aguaPotable: true,
                aguasResiduales: false
            },
            plantilla: {
                EsPlantilla: false,
                Comptador: {
                    LimInf: '5',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                PH: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: true,
                    VerInspector: false,
                },
                Temperatura: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'C',
                    Activo: true,
                    VerInspector: false,
                },
                Conductivitat: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: false,
                    VerInspector: false,
                },
                AlcalinitatM: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                AlcalinitatP: {

                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: false,
                },
                DuresaCalcica: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                DuresaTotal: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: true,
                },
                Terbolesa: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: false,
                },
                Fe: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                Clorurs: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: true,
                },
                Sulfots: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: true,
                    VerInspector: true,
                },
                ClorLliure: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'C',
                    Activo: false,
                    VerInspector: false,
                },
                ClorTotal: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: false,
                    VerInspector: false,
                },
                Brom: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'mg/l',
                    Activo: false,
                    VerInspector: false,
                },
                Sulfits: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                Campo1_Nombre: '',
                Campo1_LimInf: '',
                Campo1_LimSup: '',
                Campo1_Unidades: 'm3',
                Campo1_Activo: false,
                Campo1_VerInspector: false,
                Campo2_Nombre: '',
                Campo2_LimInf: '',
                Campo2_LimSup: '',
                Campo2_Unidades: 'm3',
                Campo2_Activo: false,
                Campo2_VerInspector: false,
                Campo3_Nombre: '',
                Campo3_LimInf: '',
                Campo3_LimSup: '',
                Campo3_Unidades: 'm3',
                Campo3_Activo: false,
                Campo3_VerInspector: false,
                Campo4_Nombre: '',
                Campo4_LimInf: '',
                Campo4_LimSup: '',
                Campo4_Unidades: 'm3',
                Campo4_Activo: false,
                Campo4_VerInspector: false,
                Campo5_Nombre: '',
                Campo5_LimInf: '',
                Campo5_LimSup: '',
                Campo5_Unidades: 'm3',
                Campo5_Activo: false,
                Campo5_VerInspector: false,
                Campo6_Nombre: '',
                Campo6_LimInf: '',
                Campo6_LimSup: '',
                Campo6_Unidades: 'm3',
                Campo6_Activo: false,
                Campo6_VerInspector: false,
                Campo7_Nombre: '',
                Campo7_LimInf: '',
                Campo7_LimSup: '',
                Campo7_Unidades: 'm3',
                Campo7_Activo: false,
                Campo7_VerInspector: false,
                Campo8_Nombre: '',
                Campo8_LimInf: '',
                Campo8_LimSup: '',
                Campo8_Unidades: 'm3',
                Campo8_Activo: false,
                Campo8_VerInspector: false,
                Campo9_Nombre: '',
                Campo9_LimInf: '',
                Campo9_LimSup: '',
                Campo9_Unidades: 'm3',
                Campo9_Activo: false,
                Campo9_VerInspector: false,
                Campo10_Nombre: '',
                Campo10_LimInf: '',
                Campo10_LimSup: '',
                Campo10_Unidades: 'm3',
                Campo10_Activo: false,
                Campo10_VerInspector: false,
                Campo11_Nombre: '',
                Campo11_LimInf: '',
                Campo11_LimSup: '',
                Campo11_Unidades: 'm3',
                Campo11_Activo: false,
                Campo11_VerInspector: false,
                Campo12_Nombre: '',
                Campo12_LimInf: '',
                Campo12_LimSup: '',
                Campo12_Unidades: 'm3',
                Campo12_Activo: false,
                Campo12_VerInspector: false,
            }
        },
        {
            nombre: 'Depósito',
            numero: 1,
            posicion: 1,
            nivel: 2,
            propiedades: {
                fisicoQuimico: true,
                aerobios: true,
                legionela: true,
                aguaPotable: true,
                aguasResiduales: false
            },
            plantilla: {
                EsPlantilla: false,
                Comptador: {
                    LimInf: '5',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                PH: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: true,
                    VerInspector: false,
                },
                Temperatura: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'C',
                    Activo: true,
                    VerInspector: false,
                },
                Conductivitat: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: false,
                    VerInspector: false,
                },
                AlcalinitatM: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                AlcalinitatP: {

                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: false,
                },
                DuresaCalcica: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                DuresaTotal: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: true,
                },
                Terbolesa: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: false,
                },
                Fe: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                Clorurs: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: true,
                },
                Sulfots: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: true,
                    VerInspector: true,
                },
                ClorLliure: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'C',
                    Activo: false,
                    VerInspector: false,
                },
                ClorTotal: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: false,
                    VerInspector: false,
                },
                Brom: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'mg/l',
                    Activo: false,
                    VerInspector: false,
                },
                Sulfits: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                Campo1_Nombre: '',
                Campo1_LimInf: '',
                Campo1_LimSup: '',
                Campo1_Unidades: 'm3',
                Campo1_Activo: false,
                Campo1_VerInspector: false,
                Campo2_Nombre: '',
                Campo2_LimInf: '',
                Campo2_LimSup: '',
                Campo2_Unidades: 'm3',
                Campo2_Activo: false,
                Campo2_VerInspector: false,
                Campo3_Nombre: '',
                Campo3_LimInf: '',
                Campo3_LimSup: '',
                Campo3_Unidades: 'm3',
                Campo3_Activo: false,
                Campo3_VerInspector: false,
                Campo4_Nombre: '',
                Campo4_LimInf: '',
                Campo4_LimSup: '',
                Campo4_Unidades: 'm3',
                Campo4_Activo: false,
                Campo4_VerInspector: false,
                Campo5_Nombre: '',
                Campo5_LimInf: '',
                Campo5_LimSup: '',
                Campo5_Unidades: 'm3',
                Campo5_Activo: false,
                Campo5_VerInspector: false,
                Campo6_Nombre: '',
                Campo6_LimInf: '',
                Campo6_LimSup: '',
                Campo6_Unidades: 'm3',
                Campo6_Activo: false,
                Campo6_VerInspector: false,
                Campo7_Nombre: '',
                Campo7_LimInf: '',
                Campo7_LimSup: '',
                Campo7_Unidades: 'm3',
                Campo7_Activo: false,
                Campo7_VerInspector: false,
                Campo8_Nombre: '',
                Campo8_LimInf: '',
                Campo8_LimSup: '',
                Campo8_Unidades: 'm3',
                Campo8_Activo: false,
                Campo8_VerInspector: false,
                Campo9_Nombre: '',
                Campo9_LimInf: '',
                Campo9_LimSup: '',
                Campo9_Unidades: 'm3',
                Campo9_Activo: false,
                Campo9_VerInspector: false,
                Campo10_Nombre: '',
                Campo10_LimInf: '',
                Campo10_LimSup: '',
                Campo10_Unidades: 'm3',
                Campo10_Activo: false,
                Campo10_VerInspector: false,
                Campo11_Nombre: '',
                Campo11_LimInf: '',
                Campo11_LimSup: '',
                Campo11_Unidades: 'm3',
                Campo11_Activo: false,
                Campo11_VerInspector: false,
                Campo12_Nombre: '',
                Campo12_LimInf: '',
                Campo12_LimSup: '',
                Campo12_Unidades: 'm3',
                Campo12_Activo: false,
                Campo12_VerInspector: false,
            }
        },
        {
            nombre: 'Osmosis',
            numero: 1,
            posicion: 2,
            nivel: 2,
            propiedades: {
                fisicoQuimico: false,
                aerobios: false,
                legionela: true,
                aguaPotable: false,
                aguasResiduales: true
            },
            plantilla: {
                EsPlantilla: false,
                Comptador: {
                    LimInf: '5',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                PH: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: true,
                    VerInspector: false,
                },
                Temperatura: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'C',
                    Activo: true,
                    VerInspector: false,
                },
                Conductivitat: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: false,
                    VerInspector: false,
                },
                AlcalinitatM: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                AlcalinitatP: {

                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: false,
                },
                DuresaCalcica: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                DuresaTotal: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: true,
                },
                Terbolesa: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: false,
                },
                Fe: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                Clorurs: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: true,
                },
                Sulfots: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: true,
                    VerInspector: true,
                },
                ClorLliure: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'C',
                    Activo: false,
                    VerInspector: false,
                },
                ClorTotal: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: false,
                    VerInspector: false,
                },
                Brom: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'mg/l',
                    Activo: false,
                    VerInspector: false,
                },
                Sulfits: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                Campo1_Nombre: '',
                Campo1_LimInf: '',
                Campo1_LimSup: '',
                Campo1_Unidades: 'm3',
                Campo1_Activo: false,
                Campo1_VerInspector: false,
                Campo2_Nombre: '',
                Campo2_LimInf: '',
                Campo2_LimSup: '',
                Campo2_Unidades: 'm3',
                Campo2_Activo: false,
                Campo2_VerInspector: false,
                Campo3_Nombre: '',
                Campo3_LimInf: '',
                Campo3_LimSup: '',
                Campo3_Unidades: 'm3',
                Campo3_Activo: false,
                Campo3_VerInspector: false,
                Campo4_Nombre: '',
                Campo4_LimInf: '',
                Campo4_LimSup: '',
                Campo4_Unidades: 'm3',
                Campo4_Activo: false,
                Campo4_VerInspector: false,
                Campo5_Nombre: '',
                Campo5_LimInf: '',
                Campo5_LimSup: '',
                Campo5_Unidades: 'm3',
                Campo5_Activo: false,
                Campo5_VerInspector: false,
                Campo6_Nombre: '',
                Campo6_LimInf: '',
                Campo6_LimSup: '',
                Campo6_Unidades: 'm3',
                Campo6_Activo: false,
                Campo6_VerInspector: false,
                Campo7_Nombre: '',
                Campo7_LimInf: '',
                Campo7_LimSup: '',
                Campo7_Unidades: 'm3',
                Campo7_Activo: false,
                Campo7_VerInspector: false,
                Campo8_Nombre: '',
                Campo8_LimInf: '',
                Campo8_LimSup: '',
                Campo8_Unidades: 'm3',
                Campo8_Activo: false,
                Campo8_VerInspector: false,
                Campo9_Nombre: '',
                Campo9_LimInf: '',
                Campo9_LimSup: '',
                Campo9_Unidades: 'm3',
                Campo9_Activo: false,
                Campo9_VerInspector: false,
                Campo10_Nombre: '',
                Campo10_LimInf: '',
                Campo10_LimSup: '',
                Campo10_Unidades: 'm3',
                Campo10_Activo: false,
                Campo10_VerInspector: false,
                Campo11_Nombre: '',
                Campo11_LimInf: '',
                Campo11_LimSup: '',
                Campo11_Unidades: 'm3',
                Campo11_Activo: false,
                Campo11_VerInspector: false,
                Campo12_Nombre: '',
                Campo12_LimInf: '',
                Campo12_LimSup: '',
                Campo12_Unidades: 'm3',
                Campo12_Activo: false,
                Campo12_VerInspector: false,
            }
        },
        {
            nombre: 'Torre',
            numero: 1,
            posicion: 1,
            nivel: 3,
            propiedades: {
                fisicoQuimico: false,
                aerobios: false,
                legionela: true,
                aguaPotable: true,
                aguasResiduales: true
            },
            plantilla: {
                EsPlantilla: false,
                Comptador: {
                    LimInf: '5',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                PH: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: true,
                    VerInspector: false,
                },
                Temperatura: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'C',
                    Activo: true,
                    VerInspector: false,
                },
                Conductivitat: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: false,
                    VerInspector: false,
                },
                AlcalinitatM: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                AlcalinitatP: {

                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: false,
                },
                DuresaCalcica: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                DuresaTotal: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: true,
                },
                Terbolesa: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: false,
                },
                Fe: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                Clorurs: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: true,
                },
                Sulfots: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: true,
                    VerInspector: true,
                },
                ClorLliure: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'C',
                    Activo: false,
                    VerInspector: false,
                },
                ClorTotal: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: false,
                    VerInspector: false,
                },
                Brom: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'mg/l',
                    Activo: false,
                    VerInspector: false,
                },
                Sulfits: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                Campo1_Nombre: '',
                Campo1_LimInf: '',
                Campo1_LimSup: '',
                Campo1_Unidades: 'm3',
                Campo1_Activo: false,
                Campo1_VerInspector: false,
                Campo2_Nombre: '',
                Campo2_LimInf: '',
                Campo2_LimSup: '',
                Campo2_Unidades: 'm3',
                Campo2_Activo: false,
                Campo2_VerInspector: false,
                Campo3_Nombre: '',
                Campo3_LimInf: '',
                Campo3_LimSup: '',
                Campo3_Unidades: 'm3',
                Campo3_Activo: false,
                Campo3_VerInspector: false,
                Campo4_Nombre: '',
                Campo4_LimInf: '',
                Campo4_LimSup: '',
                Campo4_Unidades: 'm3',
                Campo4_Activo: false,
                Campo4_VerInspector: false,
                Campo5_Nombre: '',
                Campo5_LimInf: '',
                Campo5_LimSup: '',
                Campo5_Unidades: 'm3',
                Campo5_Activo: false,
                Campo5_VerInspector: false,
                Campo6_Nombre: '',
                Campo6_LimInf: '',
                Campo6_LimSup: '',
                Campo6_Unidades: 'm3',
                Campo6_Activo: false,
                Campo6_VerInspector: false,
                Campo7_Nombre: '',
                Campo7_LimInf: '',
                Campo7_LimSup: '',
                Campo7_Unidades: 'm3',
                Campo7_Activo: false,
                Campo7_VerInspector: false,
                Campo8_Nombre: '',
                Campo8_LimInf: '',
                Campo8_LimSup: '',
                Campo8_Unidades: 'm3',
                Campo8_Activo: false,
                Campo8_VerInspector: false,
                Campo9_Nombre: '',
                Campo9_LimInf: '',
                Campo9_LimSup: '',
                Campo9_Unidades: 'm3',
                Campo9_Activo: false,
                Campo9_VerInspector: false,
                Campo10_Nombre: '',
                Campo10_LimInf: '',
                Campo10_LimSup: '',
                Campo10_Unidades: 'm3',
                Campo10_Activo: false,
                Campo10_VerInspector: false,
                Campo11_Nombre: '',
                Campo11_LimInf: '',
                Campo11_LimSup: '',
                Campo11_Unidades: 'm3',
                Campo11_Activo: false,
                Campo11_VerInspector: false,
                Campo12_Nombre: '',
                Campo12_LimInf: '',
                Campo12_LimSup: '',
                Campo12_Unidades: 'm3',
                Campo12_Activo: false,
                Campo12_VerInspector: false,
            }
        },
        {
            nombre: 'Torre',
            numero: 2,
            posicion: 2,
            nivel: 3,
            propiedades: {
                fisicoQuimico: true,
                aerobios: false,
                legionela: false,
                aguaPotable: true,
                aguasResiduales: true
            },
            plantilla: {
                EsPlantilla: false,
                Comptador: {
                    LimInf: '5',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                PH: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: true,
                    VerInspector: false,
                },
                Temperatura: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'C',
                    Activo: true,
                    VerInspector: false,
                },
                Conductivitat: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: false,
                    VerInspector: false,
                },
                AlcalinitatM: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                AlcalinitatP: {

                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: false,
                },
                DuresaCalcica: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                DuresaTotal: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: true,
                },
                Terbolesa: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: false,
                },
                Fe: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                Clorurs: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: true,
                },
                Sulfots: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: true,
                    VerInspector: true,
                },
                ClorLliure: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'C',
                    Activo: false,
                    VerInspector: false,
                },
                ClorTotal: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: false,
                    VerInspector: false,
                },
                Brom: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'mg/l',
                    Activo: false,
                    VerInspector: false,
                },
                Sulfits: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                Campo1_Nombre: '',
                Campo1_LimInf: '',
                Campo1_LimSup: '',
                Campo1_Unidades: 'm3',
                Campo1_Activo: false,
                Campo1_VerInspector: false,
                Campo2_Nombre: '',
                Campo2_LimInf: '',
                Campo2_LimSup: '',
                Campo2_Unidades: 'm3',
                Campo2_Activo: false,
                Campo2_VerInspector: false,
                Campo3_Nombre: '',
                Campo3_LimInf: '',
                Campo3_LimSup: '',
                Campo3_Unidades: 'm3',
                Campo3_Activo: false,
                Campo3_VerInspector: false,
                Campo4_Nombre: '',
                Campo4_LimInf: '',
                Campo4_LimSup: '',
                Campo4_Unidades: 'm3',
                Campo4_Activo: false,
                Campo4_VerInspector: false,
                Campo5_Nombre: '',
                Campo5_LimInf: '',
                Campo5_LimSup: '',
                Campo5_Unidades: 'm3',
                Campo5_Activo: false,
                Campo5_VerInspector: false,
                Campo6_Nombre: '',
                Campo6_LimInf: '',
                Campo6_LimSup: '',
                Campo6_Unidades: 'm3',
                Campo6_Activo: false,
                Campo6_VerInspector: false,
                Campo7_Nombre: '',
                Campo7_LimInf: '',
                Campo7_LimSup: '',
                Campo7_Unidades: 'm3',
                Campo7_Activo: false,
                Campo7_VerInspector: false,
                Campo8_Nombre: '',
                Campo8_LimInf: '',
                Campo8_LimSup: '',
                Campo8_Unidades: 'm3',
                Campo8_Activo: false,
                Campo8_VerInspector: false,
                Campo9_Nombre: '',
                Campo9_LimInf: '',
                Campo9_LimSup: '',
                Campo9_Unidades: 'm3',
                Campo9_Activo: false,
                Campo9_VerInspector: false,
                Campo10_Nombre: '',
                Campo10_LimInf: '',
                Campo10_LimSup: '',
                Campo10_Unidades: 'm3',
                Campo10_Activo: false,
                Campo10_VerInspector: false,
                Campo11_Nombre: '',
                Campo11_LimInf: '',
                Campo11_LimSup: '',
                Campo11_Unidades: 'm3',
                Campo11_Activo: false,
                Campo11_VerInspector: false,
                Campo12_Nombre: '',
                Campo12_LimInf: '',
                Campo12_LimSup: '',
                Campo12_Unidades: 'm3',
                Campo12_Activo: false,
                Campo12_VerInspector: false,
            }
        },
        {
            nombre: 'Caldera',
            numero: 1,
            posicion: 1,
            nivel: 4,
            propiedades: {
                fisicoQuimico: false,
                aerobios: true,
                legionela: true,
                aguaPotable: false,
                aguasResiduales: false
            },
            plantilla: {
                EsPlantilla: false,
                Comptador: {
                    LimInf: '5',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                PH: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: true,
                    VerInspector: false,
                },
                Temperatura: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'C',
                    Activo: true,
                    VerInspector: false,
                },
                Conductivitat: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: false,
                    VerInspector: false,
                },
                AlcalinitatM: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                AlcalinitatP: {

                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: false,
                },
                DuresaCalcica: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                DuresaTotal: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: true,
                },
                Terbolesa: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: false,
                },
                Fe: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                Clorurs: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: true,
                    VerInspector: true,
                },
                Sulfots: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: true,
                    VerInspector: true,
                },
                ClorLliure: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'C',
                    Activo: false,
                    VerInspector: false,
                },
                ClorTotal: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'Un. p',
                    Activo: false,
                    VerInspector: false,
                },
                Brom: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'mg/l',
                    Activo: false,
                    VerInspector: false,
                },
                Sulfits: {
                    LimInf: '',
                    LimSup: '',
                    Unidades: 'm3',
                    Activo: false,
                    VerInspector: false,
                },
                Campo1_Nombre: '',
                Campo1_LimInf: '',
                Campo1_LimSup: '',
                Campo1_Unidades: 'm3',
                Campo1_Activo: false,
                Campo1_VerInspector: false,
                Campo2_Nombre: '',
                Campo2_LimInf: '',
                Campo2_LimSup: '',
                Campo2_Unidades: 'm3',
                Campo2_Activo: false,
                Campo2_VerInspector: false,
                Campo3_Nombre: '',
                Campo3_LimInf: '',
                Campo3_LimSup: '',
                Campo3_Unidades: 'm3',
                Campo3_Activo: false,
                Campo3_VerInspector: false,
                Campo4_Nombre: '',
                Campo4_LimInf: '',
                Campo4_LimSup: '',
                Campo4_Unidades: 'm3',
                Campo4_Activo: false,
                Campo4_VerInspector: false,
                Campo5_Nombre: '',
                Campo5_LimInf: '',
                Campo5_LimSup: '',
                Campo5_Unidades: 'm3',
                Campo5_Activo: false,
                Campo5_VerInspector: false,
                Campo6_Nombre: '',
                Campo6_LimInf: '',
                Campo6_LimSup: '',
                Campo6_Unidades: 'm3',
                Campo6_Activo: false,
                Campo6_VerInspector: false,
                Campo7_Nombre: '',
                Campo7_LimInf: '',
                Campo7_LimSup: '',
                Campo7_Unidades: 'm3',
                Campo7_Activo: false,
                Campo7_VerInspector: false,
                Campo8_Nombre: '',
                Campo8_LimInf: '',
                Campo8_LimSup: '',
                Campo8_Unidades: 'm3',
                Campo8_Activo: false,
                Campo8_VerInspector: false,
                Campo9_Nombre: '',
                Campo9_LimInf: '',
                Campo9_LimSup: '',
                Campo9_Unidades: 'm3',
                Campo9_Activo: false,
                Campo9_VerInspector: false,
                Campo10_Nombre: '',
                Campo10_LimInf: '',
                Campo10_LimSup: '',
                Campo10_Unidades: 'm3',
                Campo10_Activo: false,
                Campo10_VerInspector: false,
                Campo11_Nombre: '',
                Campo11_LimInf: '',
                Campo11_LimSup: '',
                Campo11_Unidades: 'm3',
                Campo11_Activo: false,
                Campo11_VerInspector: false,
                Campo12_Nombre: '',
                Campo12_LimInf: '',
                Campo12_LimSup: '',
                Campo12_Unidades: 'm3',
                Campo12_Activo: false,
                Campo12_VerInspector: false,
            }
        }]
    }
    let listaElementos = planta.elementos;

    const [value, setValue] = React.useState('0');

    const handleChange = (event, newValue) => {
        setValue(newValue);
    };

    return (
    <div className="contenedor">
        <div className='cliente'>
            <h6>Cliente</h6>
            <hr/>
            <p>Test</p>
            <p>Otro test</p>
        </div>
        <TabContext value={value}>
            <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
                <TabList id="tab-list" onChange={handleChange} aria-label="basic tabs example">
                    {
                        listaElementos.map((elemento,index) => <Tab key={index} label={elemento.nombre+' '+elemento.numero} value={index.toString()} />)
                    }
                </TabList>
            </Box>

            {
                listaElementos.map((elemento,index) => <TablaElementosTabla key={index} nombre={elemento.nombre} value={index} plantilla={elemento.plantilla} />)
            }
        </TabContext>
    </div>
    );
}

export default PlantasTabla;